void 0===Object.create&&(Object.create=function(b){function c(){}c.prototype=b;return new c});function a(b,c){for(var d in c)c.hasOwnProperty(d)&&(b[d]=c[d])}function f(b,c){for(;b instanceof h;)b=c?b.value():b.f?b.value:(b.value=b.value(),b.f=!0,b.value);return b}function h(b){this.f=!1;this.value=b}function k(b){this.value=b}function l(b){return function(c){return n(b)(function(){return c})}}function n(b){return function(c){return new h(function(){var d=f(b,!0);return f(c)(d.value)})}}
function q(b){return new k(b)}
function r(b,c){var d=b[0],e=b[1];if("action"==d)return function(){return r(e[0],f(c,!0).value)};if("function"==d)return function(){var b=c,d=e[e.length-1],g=e.length;if(1<g){b=f(b,!0);if("automatic_function"==e){for(var t=0;t<arguments.length;t++)b=r(["automatic"],f(b(s(["automatic"],arguments[t])),!0));return b}for(t=0;t<g-1&&b instanceof Function;t++)b=f(b(s(e[t],arguments[t])),!0);g=d[1];return"action"==d[0]?r(g[0],b.value):r(d,b)}throw Error("Nullary function?");};if("string"==d)return u(c);
if("list"==d){d=[];for(c=f(c);c instanceof v;)d.push(r(e[0],c.e)),c=f(c.c);return d}if("tuple"==d){d=[];c=f(c);for(var g=0;c instanceof v;)d.push(r(e[g++],c.e)),c=f(c.c);return d}if("defined"==d)return c=f(c),c instanceof w?void 0:r(e[0],c.a);if("nullable"==d)return c=f(c),c instanceof x?null:r(e[0],c.a);if("double"==d||"int"==d||"bool"==d)return f(c);if("ptr"==d||"unknown"==d)return c;if("automatic"==d&&c instanceof Function)return r(["function","automatic_function"],c);if("automatic"==d||"user"==
d){c=f(c);if(c instanceof v||null===c){for(d=[];c instanceof v;)d.push(r(["automatic"],c.e)),c=f(c.c);return d}return(d=c&&c.b&&z[c.b])?d(b,b[2],c):c}throw Error("Unhandled Fay->JS translation type: "+d);}var z={};function u(b){var c="";for(b=f(b);b instanceof v;)c+=f(b.e),b=f(b.c);return c}function aa(b){return A(b)}
function s(b,c){var d=b[0],e=b[1],g;if("action"==d)return new k(s(e[0],c));if("function"==d){var m=e[e.length-1],p=e.slice(0,-1);if(0<c.length){var y=function(b){return function(d){d=r(p[b.length],d);var e=b.concat([d]);return e.length==p.length?new h(function(){return s(m,c.apply(this,e))}):y(e)}};return y([])}return function(b){return s(["automatic"],c(r(["automatic"],b)))}}if("string"==d)return A(c);if("list"==d){var t=[];g=0;for(d=c.length;g<d;g++)t.push(s(e[0],c[g]));return A(t)}if("tuple"==
d){t=[];g=0;for(d=c.length;g<d;g++)t.push(s(e[g],c[g]));return A(t)}if("defined"==d)return void 0===c?new w:new ba(s(e[0],c));if("nullable"==d)return null===c?new x:new ca(s(e[0],c));if("int"==d){g=Math.round(c);if(g!==c)throw"Argument "+c+" is not an integer!";return g}if("double"==d||"bool"==d||"ptr"==d||"unknown"==d)return c;if("automatic"==d&&c instanceof Function){b=[["automatic"]];for(g=0;g<c.length;g++)b.push(["automatic"]);return s(["function",b],c)}if("automatic"==d||"user"==d){if(c&&c.instance)return(g=
B[c.instance])?g(b,b[2],c):c;if(c instanceof Array){e=null;for(g=c.length-1;0<=g;g--)e=new v(s([d],c[g]),e);return e}return c}throw Error("Unhandled JS->Fay translation type: "+d);}var B={};function v(b,c){this.e=b;this.c=c}function A(b){for(var c=null,d=b.length-1;0<=d;d--)c=new v(b[d],c);return c}function C(b){return function(c){return new v(b,c)}}function D(b,c){for(var d=0;d<b;d++)c=f(c.c);return c.e}function da(b,c){for(var d=0;null!==b&&d<c+1;d++)b=f(b.c);return d==c}
function ea(b){return function(c){return new h(function(){return f(b)*f(c)})}}function fa(b){return function(c){return new h(function(){return f(b)+f(c)})}}function ga(b){return function(c){return new h(function(){return f(b)-f(c)})}}
function E(b,c){b=f(b);c=f(c);if(b===c)return!0;if(b instanceof Array){if(b.length!=c.length)return!1;for(var d=b.length,e=0;e<d;e++)if(!E(b[e],c[e]))return!1;return!0}if(b instanceof v&&c instanceof v){do{if(!E(b.e,c.e))return!1;b=f(b.c);c=f(c.c);if(null===b||null===c)return b===c}while(1)}else{if("object"==typeof b&&"object"==typeof c&&b&&c&&b.b===c.b){for(d in b)if(!E(b[d],c[d]))return!1;return!0}return!1}}function ha(b){return function(c){return new h(function(){return E(b,c)})}}
function ia(b){return function(c){return new h(function(){return!E(b,c)})}}function ja(b){return function(c){return new h(function(){return f(b)<f(c)})}}function F(b){this.a=b}F.prototype.b="Nullable";function ca(b){return new h(function(){return new F(b)})}function x(){}x.prototype.b="Null";function ba(b){this.a=b}ba.prototype.b="Defined";function w(){}w.prototype.b="Undefined";
a(z,{Nullable:function(b,c,d){var e={instance:"Nullable"};b=r(c&&c[0]?c[0]:"automatic"===b[0]?["automatic"]:["unknown"],d.a);void 0!==b&&(e.slot1=b);return e},Null:function(){return{instance:"Null"}},Defined:function(b,c,d){var e={instance:"Defined"};b=r(c&&c[0]?c[0]:"automatic"===b[0]?["automatic"]:["unknown"],d.a);void 0!==b&&(e.slot1=b);return e},Undefined:function(){return{instance:"Undefined"}}});
a(B,{Nullable:function(b,c,d){return new F(s(c&&c[0]?c[0]:"automatic"===b[0]?["automatic"]:["unknown"],d.slot1))},Null:function(){return new x},Defined:function(b,c,d){return new ba(s(c&&c[0]?c[0]:"automatic"===b[0]?["automatic"]:["unknown"],d.slot1))},Undefined:function(){return new w}});function G(b){this.a=b}G.prototype.b="Just";function H(b){return new h(function(){return new G(b)})}function I(){}I.prototype.b="Nothing";var J=new h(function(){return new I});function ka(b){this.a=b}
ka.prototype.b="Left";function la(b){this.a=b}la.prototype.b="Right";function ma(b){return new h(function(){return function(){return f(f(f(na)(function(b){return function(d){return new h(function(){return f(f(n)(b))(function(b){return f(f(n)(d))(function(c){return f(q)(f(f(C)(b))(c))})})})}}))(f(q)(null)))(b)}()})}function oa(){}oa.prototype.b="GT";function pa(){}pa.prototype.b="LT";function qa(){}qa.prototype.b="EQ";function ra(b){return new h(function(){return f(b)?!1:!0})}
function sa(b){return new h(function(){return aa(JSON.stringify(r(["automatic"],b)))})}function K(b){return new h(function(){throw u(b);})}function L(b){return function(c){return function(d){return new h(function(){return f(b)(f(c)(d))})}}}function M(b){return function(c){return new h(function(){return f(b)(c)})}}
function N(b){return function(c){return new h(function(){if(null===f(c))return null;var d=f(c);if(d instanceof v){var e=d.e,d=d.c;return f(f(C)(f(b)(e)))(f(f(N)(b))(d))}throw["unhandled case in map",[b,c]];})}}function ta(b){return function(c){return new h(function(){var d=c,e=f(b);if(e instanceof v){var g=e.e,e=e.c;return f(f(C)(g))(f(f(ta)(e))(d))}d=c;if(null===f(b))return d;throw["unhandled case in conc",[b,c]];})}}var ua=new h(function(){return f(f(na)(ta))(null)});
function na(b){return function(c){return function(d){return new h(function(){if(null===f(d)){var e=c;return e}e=f(d);if(e instanceof v){var g=e.e,m=e.c,e=c;return f(f(b)(g))(f(f(f(na)(b))(e))(m))}throw["unhandled case in foldr",[b,c,d]];})}}}function O(b){return function(c){return new h(function(){return f(f(ta)(b))(c)})}}
function va(b){return function(c){return new h(function(){var d=c;if(0===f(b))return d;if(null===f(c))return null;d=f(c);if(d instanceof v)return d=d.c,f(f(f(ja)(b))(0))?c:f(f(va)(f(f(ga)(b))(1)))(d);throw["unhandled case in drop",[b,c]];})}}function P(b){return new h(function(){var c=f(b);if(c instanceof v){var d=c.e,c=c.c;return f(f(O)(f(P)(c)))(A([d]))}if(null===f(b))return null;throw["unhandled case in reverse",[b]];})}
a(z,{Just:function(b,c,d){var e={instance:"Just"};b=r(c&&c[0]?c[0]:"automatic"===b[0]?["automatic"]:["unknown"],d.a);void 0!==b&&(e.slot1=b);return e},Nothing:function(){return{instance:"Nothing"}},Left:function(b,c,d){var e={instance:"Left"};b=r(c&&c[0]?c[0]:"automatic"===b[0]?["automatic"]:["unknown"],d.a);void 0!==b&&(e.slot1=b);return e},Right:function(b,c,d){var e={instance:"Right"};b=r(c&&c[1]?c[1]:"automatic"===b[0]?["automatic"]:["unknown"],d.a);void 0!==b&&(e.slot1=b);return e},GT:function(){return{instance:"GT"}},
LT:function(){return{instance:"LT"}},EQ:function(){return{instance:"EQ"}}});a(B,{Just:function(b,c,d){return new G(s(c&&c[0]?c[0]:"automatic"===b[0]?["automatic"]:["unknown"],d.slot1))},Nothing:function(){return new I},Left:function(b,c,d){return new ka(s(c&&c[0]?c[0]:"automatic"===b[0]?["automatic"]:["unknown"],d.slot1))},Right:function(b,c,d){return new la(s(c&&c[1]?c[1]:"automatic"===b[0]?["automatic"]:["unknown"],d.slot1))},GT:function(){return new oa},LT:function(){return new pa},EQ:function(){return new qa}});
function wa(b){return function(c){return new h(function(){return new k(s(["unknown"],r(["user","JSDOM",[]],b).appendChild(r(["user","JSDOM",[]],c))))})}}function xa(b){return new h(function(){return new k(s(["nullable",[["user","JSDOM",[]]]],document.getElementById(u(b))))})}function ya(b){return new h(function(){return new k(s(["user","JSDOM",[]],document.createElement(u(b))))})}
function za(b){return function(c){return new h(function(){return new k(s(["unknown"],r(["user","JSDOM",[]],b).innerText=u(c)))})}}function Aa(b){return new h(function(){return new k(aa(r(["user","JSDOM",[]],b).innerText))})}function Ba(b){return function(c){return function(d){return new h(function(){return new k(s(["unknown"],r(["user","JSDOM",[]],b).setAttribute(u(c),u(d))))})}}}
function Ca(b){return new h(function(){return new k(s(["list",[["user","JSDOM",[]]]],r(["user","JSDOM",[]],b).children))})}function Da(b){return function(c){return new h(function(){return new k(s(["unknown"],r(["user","JSDOM",[]],b).removeChild(r(["user","JSDOM",[]],c))))})}}function Ea(b){return function(c){return new h(function(){return new k(s(["nullable",[["string"]]],prompt(u(b),u(c))))})}}
function Fa(b){return new h(function(){return new k(s(["nullable",[["string"]]],r(["user","JSDOM",[]],b).id))})}function Ga(b){return function(c){return new h(function(){return new k(s(["unknown"],r(["user","JSDOM",[]],b).onclick=r(["action",[["unknown"]]],c)))})}}function Ha(b){return new h(function(){return new k(s(["list",[["user","JSDOM",[]]]],document.getElementsByClassName(u(b))))})}
function Ia(b){return new h(function(){return new k(s(["unknown"],document.onkeypress=r(["function",[["user","JS",[]],["action",[["unknown"]]]]],b)))})}function Ja(b){return new h(function(){return s(["user","JSCharCode",[]],r(["user","JS",[]],b).keyCode)})}function Ka(b){return new h(function(){return aa(String.fromCharCode(r(["user","JSCharCode",[]],b)))})}function La(b){return new h(function(){return f(Ia)(f(f(L)(b))(f(f(L)(Ka))(Ja)))})}
function Ma(b){return function(c){return new h(function(){if(null===f(c)){var d=b;return null}if(da(f(c),1)){var e=D(0,f(c));return A([e])}d=f(c);if(d instanceof v){var e=d.e,g=d.c,d=b;return f(f(C)(e))(f(f(C)(d))(f(f(Ma)(d))(g)))}throw["unhandled case in myintersperse",[b,c]];})}}function Na(b){return function(c){return new h(function(){return f(f(M)(ma))(f(f(N)(b))(c))})}}function Oa(b){return function(c){return new h(function(){return f(f(l)(f(f(Na)(b))(c)))(f(q)(null))})}}
function Pa(b){return function(c){return new h(function(){if(null===f(b))return!0;if(null===f(c))return!1;var d=f(c);if(d instanceof v){var e=d.e,g=d.c,d=f(b);if(d instanceof v){var m=d.e,d=d.c;return f(f(f(ha)(m))(e))?f(f(Pa)(d))(g):!1}}throw["unhandled case in prefix",[b,c]];})}}var Qa=new h(function(){return f(f(L)(ua))(f(Ma)(A(",")))});
function Ra(b){return new h(function(){return E(b,A(""))?J:function(){function c(b){return function(e){return new h(function(){if(null===f(e)){var g=b;return A([f(P)(g),A("")])}g=f(e);if(g instanceof v&&","===f(g.e)){var m=g.c,g=b;return A([f(P)(g),m])}g=f(e);if(g instanceof v){var p=g.e,m=g.c,g=b;return f(f(c)(f(f(C)(p))(g)))(m)}throw["unhandled case in r",[b,e]];})}}return f(H)(f(f(c)(null))(b))}()})}
function Sa(b){return new h(function(){return function(){function c(b){return function(e){return new h(function(){var g=f(Ra)(e),m;if(f(g)instanceof I)m=f(P)(b);else if(f(g)instanceof G)da(f(f(g).a),2)?(m=D(0,f(f(g).a)),g=D(1,f(f(g).a)),m=f(f(c)(f(f(C)(m))(b)))(g)):m=void 0;else throw["unhandled case",g];return m})}}return f(f(c)(null))(b)}()})}
function Ta(b){return new h(function(){return"0"===f(b)?f(H)(0):"1"===f(b)?f(H)(1):"2"===f(b)?f(H)(2):"3"===f(b)?f(H)(3):"4"===f(b)?f(H)(4):"5"===f(b)?f(H)(5):"6"===f(b)?f(H)(6):"7"===f(b)?f(H)(7):"8"===f(b)?f(H)(8):"9"===f(b)?f(H)(9):J})}function Ua(b){return new h(function(){var c=f(Va)(b);if(f(c)instanceof I)c=f(K)(A("parseInt failed"));else if(f(c)instanceof G)c=f(c).a;else throw["unhandled case",c];return c})}
function Va(b){return new h(function(){return function(){function c(b){return function(e){return function(g){return new h(function(){if(null===f(g)){var m=e,p=b;return f(H)(p)}m=f(g);if(m instanceof v){var y=m.e,t=m.c,m=e,p=b,y=f(Ta)(y);if(f(y)instanceof I)m=J;else if(f(y)instanceof G)y=f(y).a,m=f(f(f(c)(f(f(fa)(p))(f(f(ea)(m))(y))))(f(f(ea)(m))(10)))(t);else throw["unhandled case",y];return m}throw["unhandled case in r",[b,e,g]];})}}}return null===f(b)?J:f(f(M)(f(f(c)(0))(1)))(f(P)(b))}()})}
function Q(b){this.a=b}Q.prototype.b="Addr";function R(b){return new h(function(){return new Q(b)})}function S(b){this.a=b}S.prototype.b="OLStr";function Wa(b){return new h(function(){return new S(b)})}function T(b,c){this.a=b;this.d=c}T.prototype.b="OL";function U(b){return function(c){return new h(function(){return new T(b,c)})}}function Xa(){}Xa.prototype.b="INDENT";function Ya(){}Ya.prototype.b="DEDENT";function Za(b){this.a=b}Za.prototype.b="LINE";
function $a(b){return new h(function(){return function(){function c(b){return new h(function(){if(E(b,A("")))return A("");var e=f(b);if(e instanceof v&&" "===f(e.e))return e=e.c,f(c)(e);e=f(b);return e instanceof v&&"\t"===f(e.e)?(e=e.c,f(c)(e)):e=b})}return f(f(M)(f(N)(function(b){return new h(function(){return"\t"===f(b)?" ":b})})))(f(f(M)(P))(f(f(M)(c))(f(f(M)(P))(f(c)(b)))))}()})}function V(b){return new h(function(){var c=f(f(M)(Wa)),d;d=f($a)(b);d=null===f(d)?A("#"):d;return c(d)})}
function ab(b){return new h(function(){if(f(b)instanceof S)return f(b).a;throw["unhandled case in unols",[b]];})}var bb=new h(function(){return V});function cb(b){return function(c){return new h(function(){return f(f(U)(f(bb)(b)))(c)})}}function W(b){return new h(function(){return f(f(U)(f(bb)(b)))(null)})}var db=new h(function(){return f(f(cb)(A("h")))(A([f(W)(A("i")),f(W)(A("j")),f(f(cb)(A("k")))(A([f(W)(A("hihihi there")),f(f(cb)(A("w")))(A([f(W)(A("t")),f(W)(A("f"))]))]))]))});
function eb(b){return new h(function(){if(f(b)instanceof Q){var c=f(b).a;return f(f(M)(Qa))(f(f(N)(sa))(c))}throw["unhandled case in addrshow",[b]];})}function fb(b){return new h(function(){return f(f(M)(R))(f(f(M)(f(N)(Ua)))(f(Sa)(b)))})}
function gb(b){return new h(function(){return function(){function c(b){return new h(function(){return 0===f(b)?A(""):f(f(f(ja)(b))(0))?f(K)(A("Bad Logic in \u2018indent\u2019")):f(f(O)(A("\t")))(f(c)(f(f(ga)(b))(1)))})}return f(f(O)(f(f(function(b){return function(e){return new h(function(){if(f(e)instanceof T){var g;f(f(e).a)instanceof S?(g=f(f(e).a).a,g=null===f(f(e).d)?f(f(O)(f(c)(b)))(g):void 0):g=void 0;return g}throw["unhandled case in r",[b,e]];})}})(0))(b)))(A("\n"))}()})}
function hb(b){return function(c){return new h(function(){return function(){function d(b){return function(c){return function(d){return new h(function(){if(f(d)instanceof T){var p;p=f(d).a;p=null===f(f(d).d)?f(f(U)(p))(null):void 0;return p}throw["unhandled case in descendAddr",[b,c,d]];})}}}return f(f(f(function(b){return function(c){return function(m){return new h(function(){var p=f(f(b)(c))(m);if(f(p)instanceof G)p=f(p).a;else if(f(p)instanceof I)p=f(f(f(d)(b))(c))(m);else throw["unhandled case",
p];return p})}}})(b))(f(R)(null)))(c)}()})}}function ib(b){return function(c){return new h(function(){return function(){function d(b){return function(c){return new h(function(){if(null===f(b))return J;if(null===f(c)){if(da(f(b),1)){var m=D(0,f(b));return f(H)(m)}return J}var p=f(c);if(p instanceof v){var m=p.e,y=p.c,p=f(b);if(p instanceof v){var t=p.e,p=p.c;return f(f(f(ha)(t))(m))?f(f(d)(p))(y):J}}throw["unhandled case in arr",[b,c]];})}}return f(f(d)(f(P)(b)))(f(P)(c))}()})}}
a(z,{Addr:function(b,c,d){b={instance:"Addr"};d=r(["list",[["int"]]],d.a);void 0!==d&&(b.slot1=d);return b},OLStr:function(b,c,d){b={instance:"OLStr"};d=u(d.a);void 0!==d&&(b.slot1=d);return b},OL:function(b,c,d){b={instance:"OL"};c=r(["user","OLStr",[]],d.a);void 0!==c&&(b.slot1=c);d=r(["list",[["user","OL",[]]]],d.d);void 0!==d&&(b.slot2=d);return b},INDENT:function(){return{instance:"INDENT"}},DEDENT:function(){return{instance:"DEDENT"}},LINE:function(b,c,d){b={instance:"LINE"};d=r(["user","OLStr",
[]],d.a);void 0!==d&&(b.slot1=d);return b}});a(B,{Addr:function(b,c,d){return new Q(s(["list",[["int"]]],d.slot1))},OLStr:function(b,c,d){return new S(A(d.slot1))},OL:function(b,c,d){return new T(s(["user","OLStr",[]],d.slot1),s(["list",[["user","OL",[]]]],d.slot2))},INDENT:function(){return new Xa},DEDENT:function(){return new Ya},LINE:function(b,c,d){return new Za(s(["user","OLStr",[]],d.slot1))}});function jb(b,c,d,e){this.a=b;this.d=c;this.g=d;this.h=e}jb.prototype.b="Node";
function kb(b){return function(c){return function(d){return function(e){return new h(function(){return new jb(b,c,d,e)})}}}}function lb(b){return new h(function(){return f(f(O)(A("olnode")))(f(eb)(b))})}function mb(b){return new h(function(){return f(f(ra)(f(f(Pa)(A("olnode")))(b)))?f(K)(A("bad id")):f(fb)(f(f(va)(6))(b))})}
function nb(b){return function(c){return new h(function(){return function(){function d(c){return new h(function(){return f(f(f(ha)(c))(b))?A([A([A("class"),A("selected")]),A([A("id"),f(lb)(c)])]):A([A([A("class"),A("unselected")]),A([A("id"),f(lb)(c)])])})}function e(b){return function(c){return new h(function(){return f(f(f(f(kb)(A("span")))(f(d)(b)))(f(H)(c)))(null)})}}var g=new h(function(){return ab});return f(function(b){return new h(function(){if(f(b)instanceof T){var c;c=f(b).a;c=null===f(f(b).d)?
f(f(f(f(kb)(A("p")))(null))(J))(A([f(f(e)(f(R)(null)))(f(g)(c))])):void 0;return c}throw["unhandled case in top",[b]];})})(c)}()})}}a(z,{Node:function(b,c,d){b={instance:"Node"};c=u(d.a);void 0!==c&&(b.slot1=c);c=r(["list",[["tuple",[["string"],["string"]]]]],d.d);void 0!==c&&(b.slot2=c);c=r(["user","Maybe",[["string"]]],d.g);void 0!==c&&(b.slot3=c);d=r(["list",[["user","DOM",[]]]],d.h);void 0!==d&&(b.slot4=d);return b}});
a(B,{Node:function(b,c,d){return new jb(A(d.slot1),s(["list",[["tuple",[["string"],["string"]]]]],d.slot2),s(["user","Maybe",[["string"]]],d.slot3),s(["list",[["user","DOM",[]]]],d.slot4))}});function X(b,c){this.a=b;this.d=c}X.prototype.b="State";function Y(b){return function(c){return new h(function(){return new X(b,c)})}}function ob(){}ob.prototype.b="SelDown";var pb=new h(function(){return new ob});function qb(){}qb.prototype.b="SelLeft";var rb=new h(function(){return new qb});
function sb(){}sb.prototype.b="SelUp";var tb=new h(function(){return new sb});function ub(){}ub.prototype.b="SelRight";var vb=new h(function(){return new ub});function wb(b){this.a=b}wb.prototype.b="Select";function xb(b){this.a=b}xb.prototype.b="Edit";function yb(b){return new h(function(){return new xb(b)})}function zb(){}zb.prototype.b="Delete";var Ab=new h(function(){return new zb});function Bb(){}Bb.prototype.b="Nada";var Cb=new h(function(){return new Bb});function Db(b){this.a=b}
Db.prototype.b="InsBefore";function Eb(b){return new h(function(){return new Db(b)})}function Fb(b){this.a=b}Fb.prototype.b="InsAfter";function Gb(b){return new h(function(){return new Fb(b)})}function Hb(b){this.a=b}Hb.prototype.b="InsAbove";function Ib(b){return new h(function(){return new Hb(b)})}function Jb(b){this.a=b}Jb.prototype.b="InsBelow";function Kb(b){return new h(function(){return new Jb(b)})}
function Lb(b){return new h(function(){if(f(b)instanceof X)return function(){if(f(f(b).a)instanceof Q)return function(){var c=f(f(b).a).a,d=f(b).d;return function(){return f(f(Y)(f(f(M)(R))(f(f(M)(P))(f(f(function(b){return function(c){return new h(function(){if(f(c)instanceof T){var d;f(c);d=null===f(b)?null:void 0;return d}throw["unhandled case in fudge",[b,c]];})}})(f(P)(c)))(d)))))(d)}()}()}();throw["unhandled case in fudgeAddr",[b]];})}
function Mb(b){return function(c){return function(d){return new h(function(){if(f(b)instanceof Q)return function(){var c=f(b).a;return function(){return f(f(hb)(function(b){return function(d){return new h(function(){if(f(b)instanceof Q){var p=f(b).a,p=f(f(ib)(c))(p);if(f(p)instanceof I)p=J;else if(f(p)instanceof G)if(f(p),f(d)instanceof T)p=null===f(f(d).d)?f(K)(A("Bad address given to olinsertAt")):void 0;else throw["unhandled case",d];else throw["unhandled case",p];return p}throw["unhandled case in f",
[b,d]];})}}))(d)}()}();throw["unhandled case in olinsertAt",[b,c,d]];})}}}function Nb(b){return function(c){return new h(function(){if(f(b)instanceof Q)return function(){var d=f(b).a;return function(){return f(f(function(b){return function(c){return new h(function(){if(null===f(b))return!0;if(f(c)instanceof T){var d;d=null===f(f(c).d)?!1:void 0;return d}throw["unhandled case in r",[b,c]];})}})(f(P)(d)))(c)}()}();throw["unhandled case in validSel",[b,c]];})}}
function Ob(b){return new h(function(){if(f(b)instanceof Q){var c=f(b).a,d=f(f(M)(R)),e;if(null===f(c))e=null;else if(e=f(c),e instanceof v)c=e.e,e=e.c,e=f(f(C)(f(f(fa)(c))(1)))(e);else throw["unhandled case",c];return d(e)}throw["unhandled case in down",[b]];})}function Pb(b){return new h(function(){if(f(b)instanceof Q){var c=f(b).a,d=f(f(M)(R));if(null===f(c))c=null;else{var e=f(c);if(e instanceof v)c=e.c;else throw["unhandled case",c];}return d(c)}throw["unhandled case in left",[b]];})}
function Qb(b){return new h(function(){if(f(b)instanceof Q){var c=f(b).a;return f(f(M)(R))(f(f(C)(0))(c))}throw["unhandled case in right",[b]];})}function Rb(b){return new h(function(){if(f(b)instanceof Q){var c=f(b).a,d=f(f(M)(R)),e;if(null===f(c))e=null;else if(e=f(c),e instanceof v)c=e.e,e=e.c,e=f(f(C)(f(f(ga)(c))(1)))(e);else throw["unhandled case",c];return d(e)}throw["unhandled case in up",[b]];})}
function Z(b){return function(c){return new h(function(){if(f(c)instanceof X){var d=f(c).a,e=f(c).d;return f(f(f(Nb)(b))(e))?f(f(Y)(b))(e):f(f(Y)(d))(e)}throw["unhandled case in moveTo",[b,c]];})}}
function Sb(b){return function(c){return function(d){return new h(function(){return function(){return f(f(hb)(function(d){return function(g){return new h(function(){var m;if(f(f(f(ia)(d))(b)))m=J;else if(f(g)instanceof T)m=null===f(f(g).d)?f(f(M)(H))(f(f(U)(c))(null)):void 0;else throw["unhandled case",g];return m})}}))(d)}()})}}}
function Tb(b){return function(c){return function(d){return new h(function(){var e=d,g=c;if(f(b)instanceof Q)return function(){if(null===f(f(b).a)){var c=f(g)(e);if(f(c)instanceof I)c=f(f(U)(f(V)(A("#"))))(null);else if(f(c)instanceof G)c=f(c).a;else throw["unhandled case",c];return c}}();e=d;g=c;if(f(b)instanceof Q)return function(){var c=f(f(b).a);if(c instanceof v){var d=c.c;return function(){return f(f(hb)(function(b){return function(c){return new h(function(){if(f(b)instanceof Q){var e=f(b).a;
if(f(f(f(ia)(e))(d)))e=J;else if(f(c)instanceof T)e=null===f(f(c).d)?J:void 0;else throw["unhandled case",c];return e}throw["unhandled case in r",[b,c]];})}}))(e)}()}}();throw["unhandled case in olreplaceAt",[b,c,d]];})}}}function Ub(b){return function(c){return function(d){return new h(function(){return function(){return f(f(M)(f(Y)(c)))(f(f(f(Tb)(c))(function(c){return new h(function(){return f(f(M)(H))(f(f(U)(b))(A([c])))})}))(d))}()})}}}
function Vb(b){return function(c){return function(d){return new h(function(){return function(){return f(f(M)(f(Wb)(vb)))(f(f(M)(f(Y)(c)))(f(f(f(Tb)(c))(function(c){return new h(function(){if(f(c)instanceof T){var d;d=f(c).a;d=null===f(f(c).d)?f(f(M)(H))(f(f(U)(d))(A([f(f(U)(b))(null)]))):void 0;return d}throw["unhandled case in r",[c]];})}))(d)))}()})}}}function Xb(b){return function(c){return new h(function(){return f(f(M)(Lb))(f(f(M)(f(Y)(b)))(f(f(f(Tb)(b))(function(){return J}))(c)))})}}
function Wb(b){return function(c){return new h(function(){if(f(c)instanceof X)return function(){var d=f(c).a,e=f(c).d;return function(b){var m;if(f(b)instanceof Bb)m=c;else if(f(b)instanceof zb)m=f(f(Xb)(d))(e);else if(f(b)instanceof xb)m=function(){var c=f(b).a;return f(f(M)(f(Y)(d)))(f(f(f(Sb)(d))(c))(e))}();else if(f(b)instanceof wb)m=function(){var d=f(b).a;return f(f(Z)(d))(c)}();else if(f(b)instanceof ob)m=f(f(Z)(f(Ob)(d)))(f(f(Y)(d))(e));else if(f(b)instanceof sb)m=f(f(Z)(f(Rb)(d)))(f(f(Y)(d))(e));
else if(f(b)instanceof qb)m=f(f(Z)(f(Pb)(d)))(f(f(Y)(d))(e));else if(f(b)instanceof ub)m=f(f(Z)(f(Qb)(d)))(f(f(Y)(d))(e));else if(f(b)instanceof Db)m=function(){var c=f(b).a;return f(f(M)(f(Y)(d)))(f(f(f(Mb)(d))(c))(e))}();else if(f(b)instanceof Fb)m=function(){var c=f(b).a;return f(f(M)(f(Y)(f(Ob)(d))))(f(f(f(Mb)(f(Ob)(d)))(c))(e))}();else if(f(b)instanceof Hb)m=function(){var c=f(b).a;return f(f(f(Ub)(c))(d))(e)}();else if(f(b)instanceof Jb)m=function(){var c=f(b).a;return f(f(f(Vb)(c))(d))(e)}();
else throw["unhandled case",b];return m}(b)}();throw["unhandled case in apply",[b,c]];})}}
a(z,{State:function(b,c,d){b={instance:"State"};c=r(["user","Addr",[]],d.a);void 0!==c&&(b.slot1=c);d=r(["user","OL",[]],d.d);void 0!==d&&(b.slot2=d);return b},SelDown:function(){return{instance:"SelDown"}},SelLeft:function(){return{instance:"SelLeft"}},SelUp:function(){return{instance:"SelUp"}},SelRight:function(){return{instance:"SelRight"}},Select:function(b,c,d){b={instance:"Select"};d=r(["user","Addr",[]],d.a);void 0!==d&&(b.slot1=d);return b},Edit:function(b,c,d){b={instance:"Edit"};d=r(["user",
"OLStr",[]],d.a);void 0!==d&&(b.slot1=d);return b},Delete:function(){return{instance:"Delete"}},Nada:function(){return{instance:"Nada"}},InsBefore:function(b,c,d){b={instance:"InsBefore"};d=r(["user","OLStr",[]],d.a);void 0!==d&&(b.slot1=d);return b},InsAfter:function(b,c,d){b={instance:"InsAfter"};d=r(["user","OLStr",[]],d.a);void 0!==d&&(b.slot1=d);return b},InsAbove:function(b,c,d){b={instance:"InsAbove"};d=r(["user","OLStr",[]],d.a);void 0!==d&&(b.slot1=d);return b},InsBelow:function(b,c,d){b=
{instance:"InsBelow"};d=r(["user","OLStr",[]],d.a);void 0!==d&&(b.slot1=d);return b}});
a(B,{State:function(b,c,d){return new X(s(["user","Addr",[]],d.slot1),s(["user","OL",[]],d.slot2))},SelDown:function(){return new ob},SelLeft:function(){return new qb},SelUp:function(){return new sb},SelRight:function(){return new ub},Select:function(b,c,d){return new wb(s(["user","Addr",[]],d.slot1))},Edit:function(b,c,d){return new xb(s(["user","OLStr",[]],d.slot1))},Delete:function(){return new zb},Nada:function(){return new Bb},InsBefore:function(b,c,d){return new Db(s(["user","OLStr",[]],d.slot1))},
InsAfter:function(b,c,d){return new Fb(s(["user","OLStr",[]],d.slot1))},InsAbove:function(b,c,d){return new Hb(s(["user","OLStr",[]],d.slot1))},InsBelow:function(b,c,d){return new Jb(s(["user","OLStr",[]],d.slot1))}});function Yb(){}Yb.prototype.b="FayRef";function Zb(b){return new h(function(){return new k(s(["user","FayRef",[["unknown"]]],{i:r(["unknown"],b)}))})}function $(b){return new h(function(){return new k(s(["unknown"],r(["user","FayRef",[["unknown"]]],b).contents))})}
function $b(b){return function(c){return new h(function(){return new k(s(["unknown"],r(["user","FayRef",[["unknown"]]],b).contents=r(["unknown"],c)))})}}function ac(b){return function(c){return new h(function(){return f(f(n)(f($)(b)))(f(f(L)(f($b)(b)))(c))})}}a(z,{FayRef:function(){return{instance:"FayRef"}}});a(B,{FayRef:function(){return new Yb}});function bc(b,c){this.a=b;this.d=c}bc.prototype.b="ADD";function cc(b){this.a=b}cc.prototype.b="DEL";function dc(b,c){this.a=b;this.d=c}
dc.prototype.b="MOV";function ec(b,c){this.a=b;this.d=c}ec.prototype.b="EDT";function fc(){}fc.prototype.b="Delete";function gc(){}gc.prototype.b="Descend";function hc(b){this.a=b}hc.prototype.b="Replace";
a(z,{ADD:function(b,c,d){b={instance:"ADD"};c=r(["user","Addr",[]],d.a);void 0!==c&&(b.slot1=c);d=r(["user","OL",[]],d.d);void 0!==d&&(b.slot2=d);return b},DEL:function(b,c,d){b={instance:"DEL"};d=r(["user","Addr",[]],d.a);void 0!==d&&(b.slot1=d);return b},MOV:function(b,c,d){b={instance:"MOV"};c=r(["user","Addr",[]],d.a);void 0!==c&&(b.slot1=c);d=r(["user","Addr",[]],d.d);void 0!==d&&(b.slot2=d);return b},EDT:function(b,c,d){b={instance:"EDT"};c=r(["user","Addr",[]],d.a);void 0!==c&&(b.slot1=c);
d=r(["user","OLStr",[]],d.d);void 0!==d&&(b.slot2=d);return b},Delete:function(){return{instance:"Delete"}},Descend:function(){return{instance:"Descend"}},Replace:function(b,c,d){var e={instance:"Replace"};b=r(c&&c[0]?c[0]:"automatic"===b[0]?["automatic"]:["unknown"],d.a);void 0!==b&&(e.slot1=b);return e}});
a(B,{ADD:function(b,c,d){return new bc(s(["user","Addr",[]],d.slot1),s(["user","OL",[]],d.slot2))},DEL:function(b,c,d){return new cc(s(["user","Addr",[]],d.slot1))},MOV:function(b,c,d){return new dc(s(["user","Addr",[]],d.slot1),s(["user","Addr",[]],d.slot2))},EDT:function(b,c,d){return new ec(s(["user","Addr",[]],d.slot1),s(["user","OLStr",[]],d.slot2))},Delete:function(){return new fc},Descend:function(){return new gc},Replace:function(b,c,d){return new hc(s(c&&c[0]?c[0]:"automatic"===b[0]?["automatic"]:
["unknown"],d.slot1))}});function ic(b){return function(c){return new h(function(){return f(f(ac)(b))(function(b){if(f(b)instanceof X)return b=f(b).d,f(f(Y)(c))(b);throw["unhandled case",b];})})}}function jc(b){return new h(function(){return f(f(n)(f($)(b)))(function(b){if(f(b)instanceof X)return b=f(b).a,f(q)(b);throw["unhandled case",b];})})}function kc(b){return new h(function(){return f($)(b)})}
function lc(b){return function(c){return new h(function(){return f(f(ac)(b))(function(){return c})})}}function mc(b){return function(c){return new h(function(){if(null===f(c)){var d=b;return f(q)(null)}d=f(c);if(d instanceof v&&da(f(d.e),2)){var e=D(0,f(d.e)),g=D(1,f(d.e)),m=d.c,d=b;return f(f(l)(f(f(f(Ba)(d))(e))(g)))(f(f(mc)(d))(m))}throw["unhandled case in setAttrs",[b,c]];})}}
var nc=new h(function(){return f(f(n)(f(xa)(A("outline"))))(function(b){if(f(b)instanceof x)b=f(K)(A("There has to be a node with id=\u201coutline\u201d in the document."));else if(f(b)instanceof F)b=f(b).a,b=f(q)(b);else throw["unhandled case",b];return b})}),oc=new h(function(){return f(f(n)(nc))(function(b){return f(f(n)(f(Ca)(b)))(f(Oa)(f(Da)(b)))})});function pc(b){return new h(function(){return f(f(n)(nc))(function(c){return f(f(wa)(c))(b)})})}
function qc(b){return new h(function(){return f(f(l)(oc))(f(pc)(b))})}
function rc(b){return new h(function(){if(f(b)instanceof jb)return function(){var c=f(b).a,d=f(b).d,e=f(b).g,g=f(b).h;return f(f(n)(f(ya)(c)))(function(b){var c=f(f(l)(f(f(mc)(b))(d))),y=f(l),t;if(f(e)instanceof I)t=f(q)(null);else if(f(e)instanceof G)t=f(e).a,t=f(f(za)(b))(t);else throw["unhandled case",e];return c(f(y(t))(f(f(l)(f(f(n)(f(f(Na)(rc))(g)))(f(Oa)(f(wa)(b)))))(f(q)(b))))})}();throw["unhandled case in gendom",[b]];})}
function sc(b){return function(c){return new h(function(){return f(f(n)(f(f(Ea)(b))(c)))(function(b){if(f(b)instanceof x)b=f(q)(c);else if(f(b)instanceof F)b=f(b).a,b=f(q)(b);else throw["unhandled case",b];return b})})}}
function tc(b){return new h(function(){return function(){return f(f(n)(f(Fa)(b)))(function(b){return new h(function(){if(f(b)instanceof x)return f(K)(A("Internal Error: Clickable node has invalid ID"));if(f(b)instanceof F){var d=f(b).a;return f(q)(f(mb)(d))}throw["unhandled case in r",[b]];})})}()})}function uc(b){return function(c){return new h(function(){return f(f(l)(f(f(n)(f(tc)(c)))(f(ic)(b))))(f(vc)(b))})}}
function wc(b){return function(c){return new h(function(){return f(f(n)(f(Aa)(b)))(function(b){return E(c,A("h"))?f(q)(rb):E(c,A("l"))?f(q)(vb):E(c,A("k"))?f(q)(tb):E(c,A("j"))?f(q)(pb):E(c,A("d"))?f(q)(Ab):E(c,A("i"))?f(f(M)(q))(f(f(M)(Eb))(f(V)(A("")))):E(c,A("a"))?f(f(M)(q))(f(f(M)(Gb))(f(V)(A("")))):E(c,A("o"))?f(f(M)(q))(f(f(M)(Kb))(f(V)(A("")))):E(c,A("O"))?f(f(M)(q))(f(f(M)(Ib))(f(V)(A("")))):E(c,A("r"))||E(c,A("\r"))?f(f(n)(f(f(sc)(A("Replace Text")))(b)))(f(f(L)(q))(f(f(L)(yb))(V))):f(q)(Cb)})})}}
function xc(b){return new h(function(){return function(){function c(b){return new h(function(){return function(){var c=new h(function(){return f(f(f(f(kb)(A("pre")))(null))(f(f(M)(H))(f(f(O)(b))(A("\n")))))(null)});return f(f(n)(f(rc)(c)))(pc)}()})}return f(La)(function(d){return new h(function(){return E(d,A("!"))?f(f(n)(f(kc)(b)))(function(b){if(f(b)instanceof X)return f(b),b=f(b).d,f(f(M)(c))(f(f(M)(gb))(b));throw["unhandled case",b];}):f(f(n)(f(jc)(b)))(function(c){return f(f(n)(f(kc)(b)))(function(g){return f(f(n)(f(f(M)(xa))(f(lb)(c))))(function(c){return f(f(n)(f(f(M)(q))(function(b){if(f(b)instanceof
x)b=f(K)(A("bad addr"));else if(f(b)instanceof F)b=f(b).a;else throw["unhandled case",b];return b}(c))))(function(c){return f(f(n)(f(f(wc)(c))(d)))(function(c){return f(f(l)(f(f(M)(f(lc)(b)))(f(f(Wb)(c))(g))))(f(vc)(b))})})})})})})})}()})}
function yc(b){return new h(function(){return f(f(n)(f($)(b)))(function(c){if(f(c)instanceof X)return function(){var d=f(c).a,e=f(c).d;return f(f(f(Nb)(d))(e))?f(q)(null):f(f(ac)(b))(function(b){if(f(b)instanceof X)return f(b),b=f(b).d,f(f(Y)(f(R)(null)))(b);throw["unhandled case",b];})}();throw["unhandled case",c];})})}
function vc(b){return new h(function(){return f(f(l)(f(yc)(b)))(f(f(n)(f($)(b)))(function(c){if(f(c)instanceof X)return function(){var d=f(c).a,e=f(c).d;return f(f(l)(f(f(n)(f(rc)(f(f(nb)(d))(e))))(qc)))(f(f(n)(f(Ha)(A("unselected"))))(f(Oa)(function(c){return f(f(Ga)(c))(f(f(uc)(b))(c))})))}();throw["unhandled case",c];}))})}f(new h(function(){return f(f(n)(f(f(M)(Zb))(f(f(Y)(f(R)(null)))(db))))(function(b){return f(f(l)(f(vc)(b)))(f(xc)(b))})}));
